name: Run Azure Login with OpenID Connect
on: [push, workflow_dispatch]

permissions:
  id-token: write
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Use Azure CLI
      uses: azure/login@v1
      with:
        # Using OpenID Connect / Workload Identity
        # Create credential with create_ci_service_principal.ps1
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Run an Azure CLI command to demonstrate we're logged in
      run: |
        echo "Logged in, these are subscriptions that SP ${{ secrets.AZURE_CLIENTID }} has access to:"
        az account list -o table --query "sort_by([].{Name:name, SubscriptionId:id}, &Name)"

        echo "Resource groups SP ${{ secrets.AZURE_CLIENTID }} has access to in '$(az account show --query name -o tsv)':"
        az group list -o table --query "sort_by([].{Name:name, ResourceId:id}, &Name)"   