name: Run Azure Login with OpenID Connect
on: [push, workflow_dispatch]

permissions:
  id-token: write
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        
    - name: Install Azure CLI beta for OpenID Connect
      run: |
        cd ../..
        CWD="$(pwd)"
        python3 -m venv oidc-venv
        . oidc-venv/bin/activate
        echo "activated environment"
        python3 -m pip install -q --upgrade pip
        echo "started installing cli beta"
        pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
        echo "***************installed cli beta*******************"
        echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH
        ls -al $CWD/oidc-venv/bin

    - name: Azure CLI login
      uses: azure/login@v1.4.0
      with:
        client-id: ${{ secrets.AZURE_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANTID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

    - name: Run a Azure CLI command to demonstrate we're logged in
      run: |
        echo "Logged in, these are subscriptions that SP ${{ secrets.AZURE_CLIENTID }} has access to:"
        az account list -o table --query "sort_by([].{Name:name, SubscriptionId:id}, &Name)"

        echo "Resource groups SP ${{ secrets.AZURE_CLIENTID }} has access to in '$(az account show --query name -o tsv)':"
        az group list -o table --query "sort_by([].{Name:name, ResourceId:id}, &Name)"   